### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Louis-9902** [p455w0rd/ToughExpansion#1]
Hey,
I got a crash while looking int the creative inventory:
http://paste.ee/p/NpTA1 line:2514

I dont know if it is a cross mod problem or not.

Mods List:
  AdvancedRocketry-1.10.2-1.0.7
  angelRingToBauble-1.10.2-0.2.1.12+45380c9
  Baubles-1.10.2-1.3.8
  BetterBuildersWands-1.10.2-0.11.0.213+c6c8177
  bigfusion-1.10.2-0.0.2.0.1
  Chisel-MC1.10.2-0.0.7.7
  disenchanter-[1.9.4]1.4
  EnderIO-1.10.2-3.1.161
  EnderCore-1.10.2-0.4.1.64-beta
  extrautils2-1.10.2-1.1.3d
  jei_1.10.2-3.14.3.402
  LibVulpes-1.10.2-0.1.13-universal
  missing_pieces-1.10.2-4.1.3
  mysticalagriculture[1.10.2]-1.3.9
  omlib-1.10.2-3.0.0-37
  openmodularturrets-1.10.2-3.0.0-42
  OptiFine_1.10.2_HD_U_D4
  p455w0rdslib-1.10.2-1.0.5
  Parallel-0.1.0
  Tesla-1.10.2-1.2.1.49
  teslafied-1.10.2-1.1.0
  Torcherino-4.2s
  ToughAsNails-1.9.4-1.0.11
  ToughAsNails-Expansion-1.10.2-1.0.0
  Hwyla-1.8.1-B13_1.10.2
  zerocore-1.10.2-0.0.8.2

**Comment by p455w0rd** [comment]
It's hard to what mod is doing it..not Tough Expansion, this  I can confirm. I've seen this error before..something is breaking JEI..If you set up a blank instance with only TAN, p455w0rd'sLib, and ToughExpansion, you can confirm this..thanks for reporting though..we need more people like you reporting bugs so we can get our stuff functional!

**Comment by Louis-9902** [comment]
OK, I've changed some things and removed some mods.

- **Report 1**: https://paste.ee/p/S6bHA
   * There is an error at line 587 from tanaddons:ac 
   * And at line 3193 is the error that occurs when my game crashes 
      (It happens when i hover over the blocks in the creative inventory)

```
Mods:
  EnderIO-1.10.2-3.1.161
  EnderCore-1.10.2-0.4.1.64-beta
  jei_1.10.2-3.14.3.402
  OptiFine_1.10.2_HD_U_D4 (I've tried it also without it isn't Optifine)
  p455w0rdslib-1.10.2-1.0.5
  Parallel-0.1.0
  Tesla-1.10.2-1.2.1.49
  teslafied-1.10.2-1.1.0
  ToughAsNails-1.9.4-1.0.11
  ToughAsNails-Expansion-1.10.2-1.0.0
  Hwyla-1.8.1-B13_1.10.2
```

- **Report 2**: https://paste.ee/p/zcdol 
    (with less mods than before only the necessary ones)

```
Mods:
  EnderIO-1.10.2-3.1.161
  EnderCore-1.10.2-0.4.1.64-beta
  jei_1.10.2-3.14.3.402
  p455w0rdslib-1.10.2-1.0.5
  Tesla-1.10.2-1.2.1.49
  teslafied-1.10.2-1.1.0
  ToughAsNails-1.9.4-1.0.11
  ToughAsNails-Expansion-1.10.2-1.0.0
```

**Comment by p455w0rd** [comment]
I am unable to reproduce this is using the following mods on forge *.2215:
![](https://puu.sh/tpJuP/54df6d81a3.png)

I get what this error is trying to say, but it just doesn't happen for me. I've tried both SSP and SMP..what OS are you on and what java version are you running?

**Comment by Louis-9902** [comment]
Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Windows 10:amd64:10.0
Forge Mod Loader version 12.18.3.2215 for Minecraft 1.10.2
And SSP
And it also shows this in JEI
![image](https://cloud.githubusercontent.com/assets/16615577/22039838/1f6219e4-dd01-11e6-8b92-0392973dfee6.png)
