### ISSUE TITLE
your items shown in other mods creative tabs

### ISSUE THREAD

**Issue by kenijey** [p455w0rd/ToughExpansion#10]
![1](https://user-images.githubusercontent.com/24831406/28828379-40447446-76d9-11e7-949e-9a733d66d755.PNG)
forge 2430, your mod latest

**Comment by p455w0rd** [comment]
derp..yeah..this is a thing you'll likely see a lot of in 1.12 cuz mojang..thank you for reporting! will get a build out asap!

**Comment by kenijey** [comment]
thx
