### ISSUE TITLE
Crash on Minecraft startup

### ISSUE THREAD

**Issue by ChellieH** [p455w0rd/ToughExpansion#12]
I have the latest Tough Expansion (1.12), Tough As Nails, Baubles and your library but Minecraft crashes on startup. It worked fine before I installed this mod.

I have put the crash log on paste bin
[https://pastebin.com/nynf98ZV
](url)

Apologies if this is something really simple.

**Comment by p455w0rd** [comment]
it doesn't appear that you have RedStone Flux installed- can you confirm this? if not, can you install it and test?

**Comment by p455w0rd** [comment]
also, this mod is dependant on another mod providing the RF (Ender IO, RFTools, Immersive Engineering, Thermal Expansion, etc) via a generator of some sort

**Comment by ChellieH** [comment]
I do not have that installed - it wasn't listed as a dependency on the
curse force mod page. I will install tomorrow and retry - thank you for
your quick response.

**Comment by p455w0rd** [comment]
this is required by p455w0rdslib in 1.12+
![RF required](http://p455w0rd.net/u/17.26.04-07.08.17.png)

**Comment by p455w0rd** [comment]
I think I found the issue..i'm assuming you're installing via Twitch App/Curse App...i'll get versions of pwlib up asap with the correct version requirements so that when you install via one of these methods, it automatically installs the correct version..thanks for the report

**Comment by p455w0rd** [comment]
hmm..you are using the latest version..this should technically work...so now I'm thinking you're not using an app for this stuff, but rather manually downloading from curseforge..if this is the case, you just missed the dependency for p455w0rd's Library
