### ISSUE TITLE
[1.12.1][Request] Additional Config Options

### ISSUE THREAD

**Issue by Alaberti** [p455w0rd/ToughExpansion#15]
Would it be possible to have more granular control over the rf/tick requirements of the Temp Regulator and Thirst Quencher? We can change how much the portable regulator uses, but not the other two. 

Also, would it be possible to allow the stored RF to be lower than the current defaults? Say, if I wanted to simulate an internal battery of 4,000 RF instead of 10,000 for numerous balance reasons.

Thank you for your time.

**Comment by p455w0rd** [comment]
Working on this now :) Sorry response took so long.

**Comment by p455w0rd** [comment]
New Config File:
![New Config](http://p455w0rd.net/u/19.36.23-25.09.17.png)

This is now identical across all MC versions, will be pushing to CurseForge momentarily

**Comment by Alaberti** [comment]
Thanks!
