### ISSUE TITLE
ToughExpension refuses to launch on 1.12.2

### ISSUE THREAD

**Issue by 0Navis0** [p455w0rd/ToughExpansion#16]
ToughExpension refuses to launch on 1.12.2 and asks 1.12.2 while I'm already on it...

**Comment by p455w0rd** [comment]
?

**Comment by 0Navis0** [comment]
When I launch Minecraft, I get the screen where forge tells me ToughExpension can't be loaded because it needs 1.12 or 1.12.1 or 1.12.2, while I'm already on 1.12.2.

**Comment by p455w0rd** [comment]
well..I am getting a crash, but not due to that...there is some quirkyness going on right now with Forge..it's being looked into...but I definitely added support for all three...please paste the full filename of the ToughExpansion jar in your mods directory

**Comment by 0Navis0** [comment]
It's what I did, I just updated Forge to 14.23.0.2492, and now I get a crash. It's surely because Forge try to display the screen about the problem of compatibility with ToughExpansion but fail to it. https://pastebin.com/rgmFBjku

**Comment by p455w0rd** [comment]
yup...this is what I'm getting...I can add the Access Transformer myself and then I can further investigate...this is definitely a Forge problem

**Comment by 0Navis0** [comment]
Yeah Forge messes a lot with version compatibility between 1.12, 1.12.1, and 1.12.2.

**Comment by p455w0rd** [comment]
yup..has been reported to Forge, and I think it's a ForgeGradle problem MinecraftForge/MinecraftForge#4423

**Comment by p455w0rd** [comment]
just waiting on CurseForge approval :) it also requires the updated p455w0rdsLib which is also awaiting CurseForge approval :)
