### ISSUE TITLE
Recent updates for 1.10.2 version

### ISSUE THREAD

**Issue by grundyboy34** [p455w0rd/ToughExpansion#17]
These recent changes to the mod would be extremely helpful to have on the 1.10.2 version, and so I ported them on my fork, to a new branch named 1.10.2. I've already built, and tested it as well. 

If you could create a new branch named 1.10.2, I'll pull request to it, so that you can provide the build and provide the jar via CurseForge.

**Comment by p455w0rd** [comment]
can you join my discord please? http://p455w0rd.net/discord
