### ISSUE TITLE
Crash (1.12.2)

### ISSUE THREAD

**Issue by ghost** [p455w0rd/ToughExpansion#19]
[crash-2017-10-27_13.56.13-client.txt](https://github.com/p455w0rd/ToughExpansion/files/1421783/crash-2017-10-27_13.56.13-client.txt)
i think crash report tells everything, i'm not using ic2, using techreborn instead of it.

**Comment by p455w0rd** [comment]
fix is on CF waiting for review

**Comment by ghost** [comment]
thank you

**Comment by p455w0rd** [comment]
np, ty for the report!
