### ISSUE TITLE
Crash Report (NPE)

### ISSUE THREAD

**Issue by SethWilliamson** [p455w0rd/ToughExpansion#20]
I'm not sure what to make of this one. Note that Immersive Engineering is my only RF mod. Is there perhaps another hidden dependency? 

Crash Report:  [https://paste.ee/p/JabOP](https://paste.ee/p/JabOP) 
Full Log:  [https://paste.ee/p/OM26w](https://paste.ee/p/OM26w)

(Both expire 2018-05-11)

Game loads and plays fine when I disable ToughExpansion.

**Comment by p455w0rd** [comment]
Just tested with this setup (Minimum required) and it works fine. The class being referenced in the crash report definitely exists (the report says that TileTempRegulator can't be found)
![](http://p455w0rd.net/u/09.38.28-09.11.17.png)

It appears that you don't have Tough As Nails installed? ToughExpansion is an addon for Tough As Nails

**Comment by SethWilliamson** [comment]
I do have Tough as Nails. I do not have Redstone Flux installed. It is not listed as a dependency. Perhaps add it in the description/documentation and on Curse so it gets automatically pulled in? I assumed that Immersive Engineering which runs on RF would work to power things in your mod.

Crashed:
![crash](https://user-images.githubusercontent.com/2601547/32611259-fee3f35c-c519-11e7-8776-31ca9c4a7f61.png)

Works:
![2017-11-09 06_47_53-mods](https://user-images.githubusercontent.com/2601547/32611272-052bc852-c51a-11e7-88dc-aa0cc68c269d.png)

FWIW, I have noticed TeamCOFH's recommendation on the Redstone Flux Curse page is to use Forge Energy API. Maybe consider that to reduce the dependency chain?

**Comment by p455w0rd** [comment]
Yeah, ToughExpansion uses RF to power the items/blocks. Immersive technically doesn't need RF (It's an optional dep) as it has its own power system (cuz not enough power systems..let's make yet another?), but it can optionally be used. So yeah, it _should_ be able to run? So yeah..this makes sense. BUT...if you make another issue requesting that I use RF as an optional dependency, and Forge Energy as the primary, I'll do that :) Can't guarantee when it'll happen, but I'll get to it. For now, I updated the current 1.12 version on CurseForge to require RF. Thanks for the report though!
