### ISSUE TITLE
Cannot charge thirst quencher

### ISSUE THREAD

**Issue by viveleroi** [p455w0rd/ToughExpansion#22]
I've tried using both the Actually Additions energizer and the Immersive Engineering charging station, but the thirst quencher will not charge. I'm using ToughExpansion-1.12-3.2.10.

**Comment by p455w0rd** [comment]
ToughExpansion requires RF (RedstoneFlux is its own mod now)..So install this and it should work? I rly don't know the state of either of the mods you mentioned (whether or not they support RF any more). I would suggest that you create a new issue, requesting that I rely on Forge Energy, and optionally support RF. I would support this idea.

**Comment by viveleroi** [comment]
I had installed RedstoneFlux-1.12-2.0.1.2-universal as well but maybe it's not working as its meant to - Actually Additions still shows everything as CF and Immersive Engineering always shows it as IF (though that's always the case).

**Comment by p455w0rd** [comment]
What I know is converting to Forge Energy would solve this issue for sure. But I'm only as interested in doing it as the player is interested in doing it. So if you want this done, create a new issue ;).
