### ISSUE TITLE
How do you charge the items?

### ISSUE THREAD

**Issue by Swelem** [p455w0rd/ToughExpansion#24]
How do u charge the items and what is the role of the temperature regulator?
Would be much easier if you created a wiki
Thank you in advance

**Comment by p455w0rd** [comment]
How to charge, refer to #22 
Temp regulator will keep the temp of a room at a reasonable temperature (in Tough As Nails code, this is an integer value of 14) provided it has the energy required to run (RF currently). Basically, it does the work of Tough As Nails' cooler/heater.

**Comment by Swelem** [comment]
Do I have to install another mod other than redstone flux to charge the items?
Is there a certain charger?

**Comment by p455w0rd** [comment]
any charger that runs on RF...EnderIO (1.10.2) and Thermal Expansion (all MC versions) should work..beyond that, it  depends on if the mod supports RF and if it's enabled in configs, etc..I'll be changing the required power system from RF to FE soon which will result in a lot more mods being compatible

**Comment by Swelem** [comment]
Ok thank you
You should really create your own charger

**Comment by katubug** [comment]
We don't have EnderIO or Thermal Expansion so I'm really looking forward to the update that will allow us to actually use the items. :)
