### ISSUE TITLE
[1.12.2] Client Crash with Latest Tough as Nails (3.1.0.110)

### ISSUE THREAD

**Issue by QAngelusQ** [p455w0rd/ToughExpansion#27]
https://pastebin.com/Uv2mMQkD

I would guess it has something to do with the changes on 3.1.0.106:
"Build 1.12.2-3.1.0.106:
    Matt Caughey: Removed Freezes, added Magma Shards, tweaked crafting recipes"

**Comment by p455w0rd** [comment]
Yeah...looks like the freeze rods were removed...ill get a fix out as soon as I can...thanks for reporting

**Comment by p455w0rd** [comment]
would it be possible for you to join my discord so I can send you a copy of Tough Expansion with this fixed just to confirm that it is indeed fixed? https://discord.gg/9J7yhUP

**Comment by Voxel-Friend** [comment]
I volunteer!
