### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Winddbourne** [p455w0rd/ToughExpansion#3]
I'm getting a crash when trying to load the mod. I tried the latest version first and then back dated one and still got the crash. Here are the reports:

[crash-2017-03-04_02.31.31-client.txt](https://github.com/p455w0rd/ToughExpansion/files/818477/crash-2017-03-04_02.31.31-client.txt)

[crash-2017-03-04_02.50.28-client.txt](https://github.com/p455w0rd/ToughExpansion/files/818478/crash-2017-03-04_02.50.28-client.txt)

For now I've disabled the file but I'd really like to restore it as soon as possible. I'm aiming to let players build towns and cities so the area climate control via RF is very much something I want for my settlements. You shouldn't have to worry as much about basic survival when you are in "town" lol

**Comment by p455w0rd** [comment]
This makes no sense...This is definitely something on their end..once again. I do not reference the offending interface (ISyncedOption) anywhere in my code which means they are for some reason making it do this. The error is on ToughAsNails end. Wish I could be of more help.

**Comment by Winddbourne** [comment]
I'll look to see if they have a github and link them over to this thread that should make it easy for them to read my initial post, the error message, and also work with you if they think that is needed to help track down a conflict of some sort. :)

**Comment by p455w0rd** [comment]
yeah I'm totally willing to if they are :)

**Comment by p455w0rd** [comment]
just found it..it's on my end, but due to changes in recent TAN update..looking into it now

**Comment by p455w0rd** [comment]
just waiting on Curse :)

**Comment by Winddbourne** [comment]
Sweet! I'm glad I posted it to the Tough as Nails guys the way I did because when they come here they can instantly close the issue on their end and things will be working as soon as curse moves on things.

**Comment by p455w0rd** [comment]
u can close the issue over there :)

**Comment by Winddbourne** [comment]
Updated, launched, and successfully loaded. Good job.
