### ISSUE TITLE
[1.12.2] [Suggestion] Thirst Quencher Tweak

### ISSUE THREAD

**Issue by Voxel-Friend** [p455w0rd/ToughExpansion#30]
TAN adds Purified Water as a fluid, might be good to allow the Quencher to accept regular, dirty, and normal water fluids.

**Comment by Voxel-Friend** [comment]
For context, I was using a TE filling machine to fill it.

**Comment by Voxel-Friend** [comment]
Closing due to misunderstanding.

**Comment by p455w0rd** [comment]
nah..I'll implement this :)

**Comment by Voxel-Friend** [comment]
😁

**Comment by Voxel-Friend** [comment]
Didn't see a need for a whole new issue for just this, but the tootip for the quencher is derpy as well. screenshot in a second.

**Comment by Voxel-Friend** [comment]
![2018-04-26_19 24 19](https://user-images.githubusercontent.com/12395262/39338297-9607da40-4987-11e8-8319-1758eb1942db.png)

**Comment by Voxel-Friend** [comment]
":...tank to fill
to run.Automatically cleans water   and
Forge Energy
Automatically cleans water"

**Comment by p455w0rd** [comment]
lol..this is why I told you I still had tests to run (specifically mentioning toolltips ;) )
