### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by ghost** [p455w0rd/ToughExpansion#34]
[crash-2018-06-07_16.06.49-client.txt](https://github.com/p455w0rd/ToughExpansion/files/2080530/crash-2018-06-07_16.06.49-client.txt)

**Comment by ghost** [comment]
*removed*
it's not about this issue.

**Comment by ghost** [comment]
@mezz could it be about Forestry? or any other mod? i mean about carpenter recipies.

**Comment by mezz** [comment]
I don't know. Try removing the mod that is crashing.
If you find an issue with just Forestry alone, you can report it here: https://github.com/ForestryMC/ForestryMC/issues

**Comment by ghost** [comment]
hey ah, it happened again. it happens when i reload my world. and i think IGCM from @CreativeMD is causing also, cus i tweaked some recipies from Tough Expansion with IGCM.

**Comment by CreativeMD** [comment]
Yeah, that's an issue of IGCM, I will try to fix it.

**Comment by CreativeMD** [comment]
IGCM v1.2.0 should fix this issue and will be available soon (already uploaded it).

**Comment by ghost** [comment]
thanks a lot for your work CreativeMD! you're the man :)
