### ISSUE TITLE
Thirst Quencher Requires Uncraftable Potion

### ISSUE THREAD

**Issue by kenijey** [p455w0rd/ToughExpansion#6]
in JEI, this item requires uncraftable potion which is pink one maybe you know.
forge 2310, everything latest
![asd](https://cloud.githubusercontent.com/assets/24831406/26676377/2be053e6-46d0-11e7-89da-b0470c87130c.PNG)

**Comment by p455w0rd** [comment]
weird..thanks for the report! i'll get a hotfix out asap!
